drop table if exists users CASCADE;
create table users (
    user_type varchar(31) not null,
    user_no bigint generated by default as identity,
    age integer not null,
    create_date timestamp,
    id varchar(30) not null,
    location varchar(10) not null,
    money integer not null,
    name varchar(20) not null,
    nick_name varchar(30) not null,
    password varchar(100) not null,
    role varchar(255) not null,
    sexual varchar(6) not null,
    update_date timestamp,
    birth_date timestamp,
    business_number integer,
    primary key (user_no)
    )